name: Deploy BlazorWasm to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - "!README.md"

  workflow_dispatch:

env:
  DOTNET_VERSION: "8.0.x"
  BUILD_CONFIGURATION: Release
  PROJECT_PATH: ./src/IMC/IMC.csproj
  GITHUB_PAGES_PATH: docs

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install .NET Wasm Tools
        run: dotnet workload install wasm-tools

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration ${{env.BUILD_CONFIGURATION}} --no-restore

      - name: Publish .NET
        run: dotnet publish ${{env.PROJECT_PATH}} --configuration ${{env.BUILD_CONFIGURATION}} --output ${{env.GITHUB_PAGES_PATH}} --nologo

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{env.GITHUB_PAGES_PATH}}/www-root

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
